export const SET_ENDPOINT_SUCCESS = 'SET_ENDPOINT_SUCCESS';
export const SET_ENDPOINT_FAIL = 'SET_ENDPOINT_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const IMAGE_SUCCESS = 'IMAGE_SUCESS';
export const IMAGE_FAIL = 'IMAGE_FAIL';

export const SET_LANGUAGE_SUCCESS = 'SET_LANGUAGE_SUCCESS';
export const SET_LANGUAGE_FAIL = 'SET_LANGUAGE_FAIL';

export const ACCOUNTS_NAVIGATE = 'ACCOUNTS_NAVIGATE';



